name: Documentation

on:
  push:
    branches: [ main, master ]
    paths:
      - 'site/**/*.php'
      - 'documentation/tools/**'
      - '.github/workflows/documentation.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'site/**/*.php'
      - 'documentation/tools/**'

jobs:
  generate-documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, dom, simplexml, tokenizer

    - name: Verify phpDocumentor permissions
      run: |
        chmod +x documentation/tools/phpDocumentor.phar
        ls -la documentation/tools/phpDocumentor.phar

    - name: Generate Documentation
      run: |
        php documentation/tools/phpDocumentor.phar run -c documentation/tools/phpdoc.xml --verbose

    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v4
      with:
        name: phpdoc-documentation
        path: documentation/generated/
        retention-days: 30

    - name: Check Documentation Generated
      run: |
        if [ ! -f "documentation/generated/index.html" ]; then
          echo "❌ Documentation generation failed - index.html not found"
          exit 1
        else
          echo "✅ Documentation generated successfully"
        fi
